import React, { useState } from 'react';
import { X, Database, CheckCircle2, AlertCircle, ExternalLink, ShieldCheck, Key, Link as LinkIcon, RefreshCw, Copy, Check } from 'lucide-react';
import { getSupabaseConfig, isSupabaseConfigured } from '../utils/supabase';

export default function SupabaseConfigModal({ isOpen, onClose, onConfigSaved }) {
  const currentConfig = getSupabaseConfig();
  const [url, setUrl] = useState(currentConfig.url || '');
  const [anonKey, setAnonKey] = useState(currentConfig.anonKey || '');
  const [status, setStatus] = useState(null); // { type: 'success' | 'error', text: string }
  const [copiedSql, setCopiedSql] = useState(false);

  if (!isOpen) return null;

  const sqlSchema = `-- 1. Create Employees Table
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  internal_id text unique not null,
  emp_id text,
  is_id_not_provided boolean default false,
  name text not null,
  email text,
  company_name text default 'Neekan Consulting LLP',
  mobile text,
  linkedin text,
  blood_group text default 'O+',
  address text,
  department text default 'Software Engineer',
  role text,
  overall_exp numeric default 3.0,
  neekan_exp numeric default 1.5,
  experience text,
  joining_date date default current_date,
  pic text,
  status text default 'Active',
  skills jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

-- 2. Enable Row Level Security (RLS)
alter table public.employees enable row level security;

-- 3. Allow Public Anonymous Access for CRM Team
create policy "Allow all access to employees"
on public.employees for all
using (true)
with check (true);

-- 4. Enable Realtime Live Sync
alter publication supabase_realtime add table public.employees;`;

  const handleCopySql = () => {
    navigator.clipboard.writeText(sqlSchema);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2500);
  };

  const handleSave = (e) => {
    e.preventDefault();
    const cleanUrl = url.trim();
    const cleanKey = anonKey.trim();

    if (!cleanUrl || !cleanKey) {
      setStatus({ type: 'error', text: 'Both Supabase URL and Anon Key are required.' });
      return;
    }

    if (!cleanUrl.startsWith('http')) {
      setStatus({ type: 'error', text: 'Supabase URL must start with https://' });
      return;
    }

    localStorage.setItem('neekan_supabase_config', JSON.stringify({
      url: cleanUrl,
      anonKey: cleanKey
    }));

    setStatus({ type: 'success', text: 'Supabase credentials saved! Refreshing live database...' });
    setTimeout(() => {
      if (onConfigSaved) onConfigSaved();
      onClose();
      window.location.reload();
    }, 900);
  };

  const handleClear = () => {
    if (window.confirm('Clear saved Supabase credentials and revert to environment defaults?')) {
      localStorage.removeItem('neekan_supabase_config');
      setUrl('');
      setAnonKey('');
      setStatus({ type: 'success', text: 'Cleared local credentials.' });
      setTimeout(() => {
        if (onConfigSaved) onConfigSaved();
        onClose();
        window.location.reload();
      }, 700);
    }
  };

  const configured = isSupabaseConfigured();

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/70 backdrop-blur-xs animate-in fade-in duration-200">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl w-full max-w-2xl shadow-2xl overflow-hidden max-h-[90vh] flex flex-col">
        {/* Modal Header */}
        <div className="p-5 sm:p-6 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-600 dark:text-emerald-400">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-black text-slate-900 dark:text-white flex items-center gap-2">
                Supabase Real-Time Cloud Database
                {configured && (
                  <span className="text-[11px] font-bold px-2 py-0.5 rounded-full bg-emerald-100 dark:bg-emerald-950/80 text-emerald-700 dark:text-emerald-300 border border-emerald-300 dark:border-emerald-800 flex items-center gap-1">
                    <CheckCircle2 className="w-3 h-3 text-emerald-500" /> Connected
                  </span>
                )}
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Sync employee records live across all devices and team members
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-5 sm:p-6 space-y-5 overflow-y-auto flex-1 text-xs">
          {/* Status Message */}
          {status && (
            <div className={`p-3.5 rounded-2xl flex items-center gap-2 text-xs font-semibold ${
              status.type === 'success'
                ? 'bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-800'
                : 'bg-rose-50 dark:bg-rose-950/60 text-rose-700 dark:text-rose-300 border border-rose-200 dark:border-rose-800'
            }`}>
              {status.type === 'success' ? <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0" /> : <AlertCircle className="w-4 h-4 text-rose-500 shrink-0" />}
              <span>{status.text}</span>
            </div>
          )}

          {/* Quick Setup SQL Box */}
          <div className="bg-slate-50 dark:bg-slate-950 rounded-2xl p-4 border border-slate-200 dark:border-slate-800 space-y-2.5">
            <div className="flex items-center justify-between">
              <span className="font-bold text-slate-900 dark:text-slate-100 flex items-center gap-1.5">
                <span className="w-5 h-5 rounded-full bg-indigo-500 text-white flex items-center justify-center text-[11px] font-black">1</span>
                Run SQL Table Setup in Supabase
              </span>
              <button
                type="button"
                onClick={handleCopySql}
                className="inline-flex items-center gap-1 px-2.5 py-1 text-[11px] font-bold rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white transition-all shadow-xs"
              >
                {copiedSql ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedSql ? 'Copied SQL!' : 'Copy SQL'}</span>
              </button>
            </div>
            <p className="text-[11px] text-slate-500 dark:text-slate-400">
              Open your <strong>Supabase Dashboard → SQL Editor</strong> and paste this snippet to create the table and enable instant Realtime sync:
            </p>
            <pre className="p-3 bg-slate-900 text-slate-200 font-mono text-[10px] rounded-xl overflow-x-auto border border-slate-800 max-h-32">
              {sqlSchema}
            </pre>
          </div>

          {/* Configuration Form */}
          <form onSubmit={handleSave} className="space-y-4">
            <div className="flex items-center gap-1.5 font-bold text-slate-900 dark:text-slate-100">
              <span className="w-5 h-5 rounded-full bg-indigo-500 text-white flex items-center justify-center text-[11px] font-black">2</span>
              <span>Enter Supabase API Credentials</span>
            </div>

            <div>
              <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">
                Project URL (VITE_SUPABASE_URL)
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                  <LinkIcon className="w-4 h-4" />
                </div>
                <input
                  type="url"
                  required
                  placeholder="https://xyzcompany.supabase.co"
                  value={url}
                  onChange={(e) => setUrl(e.target.value)}
                  className="w-full pl-9 pr-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white font-mono text-xs focus:ring-2 focus:ring-emerald-500 focus:outline-none"
                />
              </div>
            </div>

            <div>
              <label className="block text-slate-700 dark:text-slate-300 font-bold mb-1">
                Project Anon API Key (VITE_SUPABASE_ANON_KEY)
              </label>
              <div className="relative">
                <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none text-slate-400">
                  <Key className="w-4 h-4" />
                </div>
                <input
                  type="password"
                  required
                  placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  value={anonKey}
                  onChange={(e) => setAnonKey(e.target.value)}
                  className="w-full pl-9 pr-3 py-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white font-mono text-xs focus:ring-2 focus:ring-emerald-500 focus:outline-none"
                />
              </div>
            </div>

            <div className="flex items-center justify-between pt-2">
              {configured && (
                <button
                  type="button"
                  onClick={handleClear}
                  className="px-3 py-2 rounded-xl text-rose-600 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/50 font-bold text-xs transition-colors"
                >
                  Clear Saved Keys
                </button>
              )}
              <div className="flex items-center gap-2 ml-auto">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-4 py-2 rounded-xl border border-slate-200 dark:border-slate-700 font-bold text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold transition-all shadow-md shadow-emerald-600/20 active:scale-95"
                >
                  Save &amp; Connect Live
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
